#!/usr/bin/env groovy

@Library('jenkins-shared-library')_
def gv

pipeline {
    agent any
    tools {
        maven 'Maven'
    }

    stages {
        stage('init') {
            steps {
                dir('java-maven-app') {
                    script {
                        gv = load "script.groovy"
                    }
                }
            }
        }

        stage('build jar') {
            steps {
                script {
                    buildjar()
                }
            }
        }
        
        stage('build images') {
            steps {
                script {
                    buildImage()
                }
            }
        }
    }
}
