def gv

pipeline {   
    agent any
    tools {
        maven 'Maven'
    }
    stages {
        stage("init") {
            when {
                expression { env.BRANCH_NAME == "master" }
            }
            steps {
                dir('java-maven-app') {
                    script {
                        gv = load "script.groovy"
                    }
                }
            }
        }

        stage("build jar") {
            when {
                expression { env.BRANCH_NAME == "master" }
            }
            steps {
                dir('java-maven-app') {
                    script {
                        gv.buildJar()
                    }
                }
            }
        }

        stage("build image") {
            when {
                expression { env.BRANCH_NAME == "master" }
            }
            steps {
                dir('java-maven-app') {
                    script {
                        gv.buildImage()
                    }
                }
            }
        }

        stage("deploy") {
            when {
                expression { env.BRANCH_NAME == "master" }
            }
            steps {
                dir('java-maven-app') {
                    script {
                        gv.deployApp()
                    }
                }
            }
        }               
    }
}
