def gv // Declare at the top for proper scope

pipeline {   
    agent any
    tools {
        maven 'Maven'
    }
    environment {
        PROJECT_DIR = 'java-maven-app'
    }
    stages {
        stage("Init") {
            steps {
                dir("${PROJECT_DIR}") {
                    script {
                        gv = load "script.groovy"
                    }
                }
            }
        }
        stage("Build Jar") {
            when {
                branch "jenkins-jobs"
            }
            steps {
                dir("${PROJECT_DIR}") {
                    script {
                        gv.buildJar()
                    }
                }
            }
        }
        stage("Build Image") {
            when {
                branch "jenkins-jobs"
            }
            steps {
                dir("${PROJECT_DIR}") {
                    script {
                        gv.buildImage()
                    }
                }
            }
        }
        stage("Deploy") {
            when {
                branch "jenkins-jobs"
            }
            steps {
                dir("${PROJECT_DIR}") {
                    script {
                        gv.deployApp()
                    }
                }
            }
        }               
    }